
name: Font Generator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:

    # checkout our repositry
    - uses: actions/checkout@v2

    # install python3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.7

    # install all dependecies
    - name: Install tools
      run: |
        pip install fontmake
        pip install git+https://github.com/typemytype/drawbot 

    # Runs a set of commands using the runners shell
    - name: Generate fonts
      run: |
        for path in ufo/*.ufo; do
          fontmake -u $path -o otf --output-dir otf
        done

    - name: Upload generated fonts
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Generated Fonts
        # A file, directory or wildcard pattern that describes what to upload
        path: otf

    - name: Build Specimen
      run: python specimen/installFontSpacingProof.py

    - name: Upload specimen
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Specimen
        # A file, directory or wildcard pattern that describes what to upload
        path: specimen.pdf


