# This is a basic workflow to help you get started with Actions

name: Font Generator

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.7
      
    # Runs a single command using the runners shell
    - name: Install tools
      run: pip install fontmake

    # Runs a set of commands using the runners shell
    - name: Generate fonts
      run: fontmake ufo/roman.ufo -o otf --output-dir generatedFonts
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Generated Fonts
        # A file, directory or wildcard pattern that describes what to upload
        path: generatedFonts
    
    
